export const DIRECTORY_PENDING = 'DIRECTORY_PENDING';
export const LOADING_MODAL = 'LOADING_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const WAIT_FOR_ENTRY = 'WAIT_FOR_ENTRY';
export const LOADING_BUNDLE = 'LOADING_BUNDLE';
export const BUNDLE_COMPLETE = 'BUNDLE_COMPLETE';
export const SHOW_STARBURST = 'SHOW_STARBURST';
