export const DIRECTORY_PENDING = 'DIRECTORY_PENDING';
export const LOADING_MODAL = 'LOADING_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const LOADING_BUNDLE = 'LOADING_BUNDLE';
export const BUNDLE_COMPLETE = 'BUNDLE_COMPLETE';

